### ISSUE TITLE
Override Hugo theme so that posts/charts/games content uses more page width

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/blog#31]
This blog uses the [ananke](https://github.com/budparr/gohugo-theme-ananke) theme with Hugo.

I'm pretty sure that ananke uses [Tachyons](https://tachyons.io/docs/table-of-properties/) properties to define things like page width.

I think that this gets updated in an override here, as I've made a previous attempt at this:
https://github.com/Leagify/blog/blob/86c560cc17e05667631fafc4ddcb990cbc523eb4/leagify/layouts/_default/single.html#L1-L21

Here's an example of the current output:
https://leagify.github.io/charts/nfl-draft-prospects-2019-04/

If this can be improved to maximize usage of page width but still be reasonably viewable on smaller screens, that would be great.

**Comment by muresan-raul** [comment]
Hello, you need something like this  https://imgur.com/a/UwiiRBo ?

**Comment by zo0o0ot** [comment]
Yeah, I think so.  I want less padding on the left and right, and to have posts take nearly all of the available horizontal space.

**Comment by muresan-raul** [comment]
I made a PR here https://github.com/Leagify/blog/pull/36
I removed those classes that were adding max width and extra padding to your single page template.
